### ISSUE TITLE
Customizable features missing

### ISSUE THREAD

**Issue by godng73** [lohanidamodar/clean_nepali_calendar#4]
You have mentioned that the calendar is highly customizable but I am only able to customize the style of the calendar. I want to customize the calendar with builder functions like in table calendar.
![image](https://user-images.githubusercontent.com/47109205/94410969-bb5c2600-0197-11eb-8dfc-2326916edf04.png)
This is the design I need but in nepali year/month and date.

**Comment by stha-ums** [comment]
i have added this feature in my fork of this project if you want to check them out, visit [fork of clean calender ](https://github.com/stha-ums/clean_nepali_calendar/tree/custombuilder).

**Comment by lohanidamodar** [comment]
Thank you for your work.
@stha-ums Can you initiate a PR, i will review and let's merge if everything goes well.

**Comment by stha-ums** [comment]
@lohanidamodar  sure, I still have some clean up to do. once i do this will request for merge.

**Comment by lohanidamodar** [comment]
Fixed by #5
